services:
  auth:
    build: ./auth
    restart: on-failure
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_HOST: 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - network
  db:
    image: postgres:18
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fullstackauthentication

    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - network
  api:
    restart: on-failure
    build: ./api
    environment:
      KEYCLOAK_JWK_SET_URI: http://auth:8080/realms/fullstackauthentication/protocol/openid-connect/certs
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: fullstackauthentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - auth
      - db
    networks:
      - network
  proxy:
    build:
      context: ./caddy
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - network
  
volumes:
  postgres_data:
  caddy_data:
  caddy_config:
networks:
  network : 