// Writes .env.local pointing the app at this Mac's current LAN IP, so builds
// run on a physical device can reach Keycloak and the API (which live on the
// Mac). Run automatically before every expo start/run script — see package.json.
import { networkInterfaces } from 'node:os';
import { writeFileSync } from 'node:fs';

function lanIp() {
  const interfaces = networkInterfaces();
  // Prefer en0 (Wi-Fi on most Macs), then any other interface.
  const names = ['en0', 'en1', ...Object.keys(interfaces)];
  for (const name of names) {
    for (const address of interfaces[name] ?? []) {
      if (address.family === 'IPv4' && !address.internal) {
        return address.address;
      }
    }
  }
  return null;
}

const ip = lanIp();
if (!ip) {
  console.warn(
    '⚠️  No LAN IP found — check Wi-Fi. Falling back to localhost, ' +
      'which only works on the simulator.',
  );
}
const host = ip ?? 'localhost';

writeFileSync(
  '.env.local',
  `# Generated by scripts/write-env.mjs — do not edit by hand.\n` +
    `EXPO_PUBLIC_API_URL=http://${host}:8001/api\n` +
    `EXPO_PUBLIC_KEYCLOAK_URL=http://${host}:8080\n`,
);
console.log(`✔ .env.local points at http://${host} (${ip ? 'LAN IP' : 'fallback'})`);